name: Upload Python Package

on: workflow_dispatch

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: x64
        
    - name: Install Python dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install numpy
        
    - name: Generate Python package
      run: |
          cd ${{github.workspace}}/pycompadre
          ./install.sh -p
          
    - uses: actions/upload-artifact@v2
      with:
        name: pycompadre.tar.gz
        path: ${{github.workspace}}/dist/*.tar.gz
      
