name: Upload Parallel Python Package (pycompadre)

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: x64
        
    - name: Install Python dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install numpy
        
    - name: Generate Python package
      run: |
          cd ${{github.workspace}}/pycompadre
          ./install.sh -p
          
    - uses: actions/upload-artifact@v2
      with:
        name: pycompadre.tar.gz
        path: ${{github.workspace}}/dist/*.tar.gz

    # https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PIP_PYCOMPADRE_SECRET }}
