name: Upload Serial Python Package

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: x64
        
    - name: Install Python dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install numpy
        
    - name: Generate Python package
      run: |
          cd ${{github.workspace}}/pycompadre
          ./install.sh -p -s
          
    - uses: actions/upload-artifact@v2
      with:
        name: pycompadre-serial.tar.gz
        path: ${{github.workspace}}/dist/*.tar.gz
      
    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PIP_PYCOMPADRE_SERIAL_SECRET }}
